### ISSUE TITLE
Missing chapters

### ISSUE THREAD

**Issue by tsoen** [sator-imaging/Unity-ReleaseNotes#3]
Hello @sator-imaging 

First of all, thank you for this tool, it is very helpful since other release notes tools did not update since the RSS feeds changes from Unity.

I noticed a lot of missing chapters for some versions, for example there is nothing between 2022.3.2 and 2022.3.26.
Do you know the reason behind it and if it could be fixed ?

Thank you very much.

**Comment by sator-imaging** [comment]
Hi,

Thank you for report. I've ran old script and uploaded missing release notes.
